<?php
	PacketHandler::registerListeners(Array(
		1 => 'LoginListener',
		2 => 'EditQuizListener',
		3 => 'AddQuizListener',
		4 => 'ApproveQuizListener',
		5 => 'DeleteQuizListener',
		6 => 'VoteQuizListener',
		7 => 'GetQuizData',
		8 => 'BookmarkQuizListener',
		9 => 'QuerySubmitListener',
		10 => 'QueryAnswerSubmitListener',
		11 => 'DeleteQueryListener',
		12 => 'RegisterAccountListener',
		13 => 'RecoverAccount',
		14 => 'ResetPassword',
		15 => 'DeleteSiteLink',
		16 => 'EditSiteLink',
		17 => 'ApproveAnswers',
		18 => 'DeleteAnswers',
		19 => 'EditAnswers',
		20 => 'AddAnswers',
		21 => 'RestoreQuiz',
		22 => 'ChangePassword',
		23 => 'ChangeEmail',
		24 => 'GetForumTopics',
		25 => 'GetForumReplies',
		26 => 'TopicComment',
		27 => 'ChangeAvatar',
		28 => 'CreateTopic',
		29 => 'EditMessage',
		30 => 'SetBroadcast',
		31 => 'ChangeForumSignature',
		32 => 'AddNewFact',
		33 => 'DeleteFact',
		34 => 'ChangeBirthday',
		35 => 'LikePostListener',
		36 => 'DeletePostListener',
		37 => 'AdminChangePasswordListener',
		38 => 'UpdateTodayTextListener'
	));
?>